#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-


def parse_snmptest(info):
    return info[::-1]


def inventory_snmptest(info):
    yield 'foo', {}
    yield 'bar', {'foo': 'bar'}


def check_snmptest(item, params, info):
    yield 0, 'SNMPTEST'

    if item == 'bar':
        yield 1, item


check_info["snmptest"] = {
    'parse_function': parse_snmptest,
    'inventory_function': inventory_snmptest,
    'check_function': check_snmptest,
    'snmp_info': ('.1.42.1', [
        OID_END,
        '1',
        '3',
    ]),
    'snmp_scan_function': lambda oid: oid(".1.42.0") == ".1.42.0"
}
